# Generated by Django 4.0.6 on 2022-07-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='sexo',
            new_name='genero',
        ),
    ]
